import{initializeApp}from"https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js";
import{getFirestore,doc,getDoc,setDoc,runTransaction,increment,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.7.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBgOAO72ArbW8dO7OSYsTVEQtRHT049U20",authDomain:"points2026-f5e50.firebaseapp.com",projectId:"points2026-f5e50"};
const db=getFirestore(initializeApp(firebaseConfig));
const ATTENDANCE_POINT=1;
const KST="Asia/Seoul";
const HOLIDAYS_2026=new Set(["2026-01-01","2026-02-16","2026-02-17","2026-02-18","2026-03-01","2026-03-02","2026-05-05","2026-05-24","2026-05-25","2026-06-03","2026-06-06","2026-08-15","2026-08-17","2026-09-24","2026-09-25","2026-09-26","2026-10-03","2026-10-05","2026-10-09","2026-12-25"]);
function kstNow(){return new Date(new Intl.DateTimeFormat("en-CA",{timeZone:KST,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).formatToParts(new Date()).reduce((o,p)=>(o[p.type]=p.value,o),{}).year+"-"+"00-00")}
function parts(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:KST,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).formatToParts(new Date());return Object.fromEntries(p.map(x=>[x.type,x.value]))}
function dateKey(){const p=parts();return `${p.year}-${p.month}-${p.day}`}
function minutes(){const p=parts();return Number(p.hour)*60+Number(p.minute)+Number(p.second)/60}
async function getClosedDates(){try{const s=await getDoc(doc(db,"attendanceSettings","main"));return s.exists()?new Set(s.data().closedDates||[]):new Set()}catch(e){console.error("[ATTENDANCE] 설정 조회 실패",e);return new Set()}}
export async function getAttendanceState(){const date=dateKey(),day=new Date(`${date}T12:00:00+09:00`).getDay(),closed=await getClosedDates();const scheduled=[1,3,5].includes(day)&&!HOLIDAYS_2026.has(date)&&!closed.has(date);const active=scheduled&&minutes()>=12*60+20&&minutes()<13*60+25;return{date,scheduled,active,minutes:minutes()}}
export async function renderAttendanceButton(button){const userId=localStorage.getItem("userId");if(!userId){button.style.display="none";return}button.style.display="block";const state=await getAttendanceState();const attRef=doc(db,"attendance",`${state.date}_${userId}`);const existing=await getDoc(attRef);if(existing.exists()){button.disabled=true;button.textContent="출석 완료";button.title="오늘 출석체크를 완료했습니다.";return}button.disabled=!state.active;if(state.active){button.textContent="출석체크";button.title="12:20~13:25 출석체크"}else if(state.scheduled){button.textContent="출석체크 준비 중";button.title="출석체크 시간: 12:20~13:25"}else{button.textContent="오늘은 출석 없음";button.title="출석체크는 월·수·금에 진행됩니다."}}
export async function checkAttendance(button){const userId=localStorage.getItem("userId");if(!userId)return location.href="/signin/?redirect=/";button.disabled=true;try{const state=await getAttendanceState();if(!state.active){alert("지금은 출석체크 시간이 아닙니다.\n출석체크 시간은 12:20~13:25입니다.");return renderAttendanceButton(button)}const userRef=doc(db,"users",userId),attRef=doc(db,"attendance",`${state.date}_${userId}`);await runTransaction(db,async tx=>{const [userSnap,attSnap]=await Promise.all([tx.get(userRef),tx.get(attRef)]);if(!userSnap.exists())throw new Error("사용자 정보를 찾을 수 없습니다.");if(attSnap.exists())throw new Error("ALREADY_ATTENDED");const data=userSnap.data();tx.update(userRef,{score:increment(ATTENDANCE_POINT)});tx.set(attRef,{userId,name:data.name||userId,student:data.student||userId,date:state.date,points:ATTENDANCE_POINT,checkedAt:serverTimestamp(),type:"attendance"})});alert(`출석체크 완료! 상점 +${ATTENDANCE_POINT}점이 지급되었습니다.`);await renderAttendanceButton(button)}catch(e){console.error("[ATTENDANCE] 출석 처리 실패",{userId,error:e});if(e.message==="ALREADY_ATTENDED")alert("이미 오늘 출석체크를 완료했습니다.");else alert("출석 처리 중 오류가 발생했습니다. 콘솔의 [ATTENDANCE] 로그를 확인하세요.");await renderAttendanceButton(button)}}
window.addEventListener("DOMContentLoaded",()=>{const button=document.getElementById("attendanceBtn");if(!button)return;button.addEventListener("click",()=>checkAttendance(button));renderAttendanceButton(button);setInterval(()=>renderAttendanceButton(button),10000)});
