import{initializeApp,getApps,getApp}from"https://www.gstatic.com/firebasejs/10.7.0/firebase-app.js";
import{getFirestore,doc,getDoc,getDocs,collection,runTransaction,increment,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.7.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBgOAO72ArW8dO7OSYsTVEQtRHT049U20",authDomain:"points2026-f5e50.firebaseapp.com",projectId:"points2026-f5e50"};
const app=getApps().some(x=>x.name==="attendanceApp")?getApp("attendanceApp"):initializeApp(firebaseConfig,"attendanceApp");
const db=getFirestore(app);
const ATTENDANCE_POINT=2,ABSENT_POINT=-5,KST="Asia/Seoul",ATTENDANCE_START_DATE="2026-09-16",ATTENDANCE_END_MINUTES=13*60+25;
const HOLIDAYS_2026=new Set(["2026-01-01","2026-02-16","2026-02-17","2026-02-18","2026-03-01","2026-03-02","2026-05-05","2026-05-24","2026-05-25","2026-06-03","2026-06-06","2026-08-15","2026-08-17","2026-09-24","2026-09-25","2026-09-26","2026-10-03","2026-10-05","2026-10-09","2026-12-25"]);
function nowParts(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:KST,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).formatToParts(new Date());return Object.fromEntries(p.map(x=>[x.type,x.value]))}
function dateKey(){const p=nowParts();return `${p.year}-${p.month}-${p.day}`}
function currentMinutes(){const p=nowParts();return Number(p.hour)*60+Number(p.minute)+Number(p.second)/60}
function weekdayFrom2026(date){const [y,m,d]=date.split("-").map(Number);const start=Date.UTC(2026,0,1),target=Date.UTC(y,m-1,d);const days=Math.round((target-start)/86400000);return (4+days)%7<0?(4+days)%7+7:(4+days)%7}
function isScheduledDate(date,closed){if(date<ATTENDANCE_START_DATE)return false;const day=weekdayFrom2026(date);return[1,3,5].includes(day)&&!HOLIDAYS_2026.has(date)&&!closed.has(date)}
function dateRange(start,end){const out=[];const d=new Date(`${start}T12:00:00+09:00`);const last=new Date(`${end}T12:00:00+09:00`);while(d<=last){out.push(new Intl.DateTimeFormat("en-CA",{timeZone:KST}).format(d));d.setUTCDate(d.getUTCDate()+1)}return out}
async function getClosedDates(){try{const s=await getDoc(doc(db,"attendanceSettings","main"));return s.exists()?new Set(Array.isArray(s.data().closedDates)?s.data().closedDates:[]):new Set()}catch(e){console.error("[ATTENDANCE] 설정 조회 실패",e);return new Set()}}
let finalizedKey="";
export async function finalizePastAttendance(force=false){const today=dateKey();const minute=currentMinutes();const runKey=`${today}-${minute>=ATTENDANCE_END_MINUTES?"expired":"open"}`;if(!force&&finalizedKey===runKey)return 0;try{const closed=await getClosedDates();const dates=dateRange(ATTENDANCE_START_DATE,today).filter(d=>isScheduledDate(d,closed)&&(d<today||(d===today&&minute>=ATTENDANCE_END_MINUTES)));if(!dates.length){finalizedKey=runKey;return 0}const usersSnap=await getDocs(collection(db,"users"));const students=usersSnap.docs.filter(s=>s.data().role==="student");let changed=0;for(const date of dates){for(const userSnap of students){const userId=userSnap.id,attRef=doc(db,"attendance",`${date}_${userId}`),userRef=doc(db,"users",userId);try{const did=await runTransaction(db,async tx=>{const [attSnap,currentUserSnap]=await Promise.all([tx.get(attRef),tx.get(userRef)]);if(attSnap.exists())return false;if(!currentUserSnap.exists()||currentUserSnap.data().role!=="student")return false;const data=currentUserSnap.data();tx.update(userRef,{score:increment(ABSENT_POINT)});tx.set(attRef,{userId,name:data.name||userId,student:data.student||userId,date,points:ABSENT_POINT,status:"absent",checkedAt:serverTimestamp(),type:"attendance",reason:"attendance_window_expired"});return true});if(did)changed++}catch(e){console.error("[ATTENDANCE] 미출석 처리 실패",{date,userId,error:e})}}}finalizedKey=runKey;if(changed)console.log("[ATTENDANCE] 미출석 자동 확정",{processed:changed,dates});return changed}catch(e){console.error("[ATTENDANCE] 지난 출석 정리 실패",e);return 0}}
export async function getAttendanceState(){const date=dateKey(),closed=await getClosedDates(),minute=currentMinutes(),scheduled=isScheduledDate(date,closed),active=scheduled&&minute>=12*60+20&&minute<ATTENDANCE_END_MINUTES;return{date,scheduled,active,expired:scheduled&&minute>=ATTENDANCE_END_MINUTES,minutes:minute}}
export async function renderAttendanceButton(button){const userId=localStorage.getItem("userId");if(!userId){button.style.display="none";return}button.style.display="block";await finalizePastAttendance();const state=await getAttendanceState();const attRef=doc(db,"attendance",`${state.date}_${userId}`),existing=await getDoc(attRef);if(existing.exists()){button.disabled=true;button.textContent=existing.data().status==="absent"?"미출석 (-5)":"출석 완료 (+2)";button.title="오늘 출석 처리가 완료되었습니다.";return}button.disabled=!state.active;if(state.active){button.textContent="출석체크 (+2)";button.title="12:20~13:25 출석체크"}else if(state.scheduled&&state.expired){button.textContent="출석 종료";button.title="오늘 출석체크 시간이 종료되었습니다."}else if(state.scheduled){button.textContent="출석체크 준비 중";button.title="출석체크 시간: 12:20~13:25"}else{button.textContent="오늘은 출석 없음";button.title="출석체크는 월·수·금에 진행됩니다."}}
export async function checkAttendance(button){const userId=localStorage.getItem("userId");if(!userId)return location.href="/signin?redirect=/";button.disabled=true;try{const state=await getAttendanceState();if(!state.active){alert("지금은 출석체크 시간이 아닙니다.\n출석체크 시간은 12:20~13:25입니다.");return}const userRef=doc(db,"users",userId),attRef=doc(db,"attendance",`${state.date}_${userId}`);await runTransaction(db,async tx=>{const [userSnap,attSnap]=await Promise.all([tx.get(userRef),tx.get(attRef)]);if(!userSnap.exists())throw new Error("USER_NOT_FOUND");if(attSnap.exists())throw new Error("ALREADY_ATTENDED");const data=userSnap.data();tx.update(userRef,{score:increment(ATTENDANCE_POINT)});tx.set(attRef,{userId,name:data.name||userId,student:data.student||userId,date:state.date,points:ATTENDANCE_POINT,status:"present",checkedAt:serverTimestamp(),type:"attendance"})});alert(`출석체크 완료! 상점 +${ATTENDANCE_POINT}점이 지급되었습니다.`);await renderAttendanceButton(button)}catch(e){console.error("[ATTENDANCE] 출석 처리 실패",{userId,error:e});if(e.message==="ALREADY_ATTENDED")alert("이미 오늘 출석 처리를 완료했습니다.");else if(e.message==="USER_NOT_FOUND")alert("사용자 정보를 찾을 수 없습니다.");else alert("출석 처리 중 오류가 발생했습니다. 콘솔의 [ATTENDANCE] 로그를 확인하세요.");await renderAttendanceButton(button)}}
window.addEventListener("DOMContentLoaded",()=>{const button=document.getElementById("attendanceBtn");if(!button)return;button.addEventListener("click",()=>checkAttendance(button));renderAttendanceButton(button).catch(e=>console.error("[ATTENDANCE] 초기화 실패",e));setInterval(()=>renderAttendanceButton(button).catch(e=>console.error("[ATTENDANCE] 갱신 실패",e)),30000)});
