import { state, $ } from "./state.js";
import { db, API_URL, doc, getDoc, getDocs, addDoc, query, orderBy, limit, startAfter, serverTimestamp, updateDoc } from "./firebase.js";
import { messagesRef, createConversation, loadChats } from "./conversations.js";
import { getProjectContext } from "./projects.js";
import { addMessage } from "./ui.js";
import { getCobyToneSettings } from "./settings.js";

export const COBY_UI_INSTRUCTIONS={name:"COBY markup",system:"COBY 답변은 전용 마크업을 사용할 수 있다. ***텍스트***는 굵게, <<<내용>>>은 복사 블록, [[[내용]]]은 경고, {{{내용}}}은 성공, (((내용)))은 팁, ---는 구분선이다. 마크업 기호 자체를 설명문으로 노출하지 않는다. 코드 복사에는 <<< >>>를 사용한다.",rules:["***text*** = bold","<<<content>>> = copy block","[[[content]]] = warning","{{{content}}} = success","(((content))) = tip","--- = divider","Do not expose delimiters","Use <<< >>> for copyable code"]};
export const COBY_USAGE_KNOWLEDGE={purpose:"COBY는 25withcoding.kr의 AI 서비스이며, 사용자가 사이트 기능 사용법을 물으면 실제 구현된 기능을 기준으로 안내한다.",rules:["사용법 질문에는 실제 구현된 기능만 안내하고 없는 기능을 있다고 말하지 않는다.","버튼이나 메뉴 위치를 물으면 클릭 순서를 단계별로 설명한다.","관리자 기능은 president 또는 vice 권한에서만 이용할 수 있다고 안내한다."],features:[{name:"새 대화",usage:"왼쪽 사이드바의 새 대화 버튼으로 새 채팅을 시작한다."},{name:"채팅 제목 수정",usage:"채팅 목록의 제목 수정 기능으로 제목을 변경한다."},{name:"휴지통",usage:"휴지통에서 삭제된 대화를 복구하거나 영구 삭제할 수 있다."},{name:"프로젝트",usage:"프로젝트를 만들고 프로젝트 아래에 대화를 연결하거나 삭제할 수 있다."},{name:"프로필 메뉴",usage:"프로필을 누르면 홈으로와 로그아웃 메뉴가 위쪽에 표시된다."},{name:"AI 과거 대화",usage:"현재 대화의 최근 기록을 우선 사용하며 이전 내용을 명확히 요청하면 필요한 과거 기록을 추가 조회한다."},{name:"관리자 대화 로그",usage:"president 또는 vice 권한만 설정에서 사용자별 대화 로그를 볼 수 있다."}]};
const extractMessage=item=>{const d=item.data();return{role:d.role,content:d.content};};
export async function getConversationHistory(){if(!state.currentConversationId)return[];const s=await getDocs(query(messagesRef(),orderBy("createdAt","desc"),limit(40)));return[...s.docs].reverse().map(extractMessage);}
export async function getOlderConversationHistory(beforeTimestamp,count=40){if(!state.currentConversationId||!beforeTimestamp)return[];const s=await getDocs(query(messagesRef(),orderBy("createdAt","desc"),startAfter(beforeTimestamp),limit(count)));return[...s.docs].reverse().map(extractMessage);}
function needsOlderHistory(text){return/(아까|이전|전에|방금 전|위에서|앞에서|처음에|지난|예전에|전에 말한|앞서|기억|전에 했던|이전 대화|이전 내용|저번|지난번)/i.test(text);}
async function getHistoryForRequest(text){if(!state.currentConversationId)return[];const s=await getDocs(query(messagesRef(),orderBy("createdAt","desc"),limit(40)));const recent=[...s.docs].reverse().map(extractMessage);if(!needsOlderHistory(text)||s.docs.length<40)return recent;const ts=s.docs[s.docs.length-1]?.data()?.createdAt;if(!ts)return recent;return[...(await getOlderConversationHistory(ts,40)),...recent];}
function extractAssistantText(data){return data?.reply??data?.response??data?.message??data?.content??data?.answer??"응답을 받지 못했습니다.";}
export async function sendMessage(){if(state.isSending)return;const input=$("userInput"),text=input.value.trim();if(!text)return;if(!state.currentUserId){alert("먼저 로그인해주세요.");return;}if(!state.currentConversationId)await createConversation(state.currentProjectId);state.isSending=true;$("sendButton").disabled=true;if($("welcome"))$("welcome").remove();try{const history=await getHistoryForRequest(text),projectContext=await getProjectContext(),tone=getCobyToneSettings();addMessage("user",text);input.value="";input.style.height="auto";await addDoc(messagesRef(),{role:"user",content:text,createdAt:serverTimestamp()});const ref=doc(db,"people",state.currentUserId,"conversations",state.currentConversationId),snap=await getDoc(ref);if(snap.exists()){const c=snap.data();await updateDoc(ref,{title:c.title&&c.title!=="새 대화"?c.title:(text.length>35?text.slice(0,35)+"…":text),updatedAt:serverTimestamp()});}const response=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,studentId:state.currentUserId,userId:state.currentUserId,conversationId:state.currentConversationId,projectId:state.currentProjectId,project:state.currentProject||null,context:projectContext,history,projectContext,user:{id:state.currentUserId,name:state.currentPerson?.name||"사용자",role:state.currentPerson?.role||"student"},uiInstructions:COBY_UI_INSTRUCTIONS,usageKnowledge:COBY_USAGE_KNOWLEDGE,toneSettings:tone})});if(!response.ok)throw new Error(`API ${response.status}`);const result=await response.json(),answer=String(extractAssistantText(result));addMessage("assistant",answer);await addDoc(messagesRef(),{role:"assistant",content:answer,createdAt:serverTimestamp()});await updateDoc(ref,{updatedAt:serverTimestamp()});await loadChats();}catch(error){console.error("AI 요청 오류:",error);addMessage("assistant",`[[[COBY 응답을 가져오지 못했습니다.]]]\n\n${error.message||"잠시 후 다시 시도해주세요."}`);}finally{state.isSending=false;$("sendButton").disabled=false;input.focus();}}
