import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc, collection, addDoc, getDocs, query, orderBy, limit, serverTimestamp, updateDoc, deleteDoc } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { renderCobyMarkup, plainCobyText, bindCobyCopy } from "./coby-markup.js";
import { initCobyInput } from "./input.js";
import { addAnswerCopyButton } from "./chat-ui.js";

const mainFirebaseConfig={apiKey:"AIzaSyBgArbW8dArbW8dO7OSYsTVEQtRHT049U20",authDomain:"points2026-f5e50.firebaseapp.com",projectId:"points2026-f5e50",storageBucket:"points2026-f5e50.firebasestorage.app",messagingSenderId:"248724251417",appId:"1:248724251417:web:02d85cdc4addac98069b88"};
const cobyFirebaseConfig={apiKey:"AIzaSyAiO65YzYeRfuf6fCzosuW7OAVV47o47Js",authDomain:"coby-ai-328dd.firebaseapp.com",projectId:"coby-ai-328dd",storageBucket:"coby-ai-328dd.firebasestorage.app",messagingSenderId:"865530259286",appId:"1:248724251417:web:6feaa5781dc538700b18f7"};
const mainDb=getFirestore(initializeApp(mainFirebaseConfig,"mainApp"));
const db=getFirestore(initializeApp(cobyFirebaseConfig,"cobyApp"));
const API_URL="https://two5withcoding.onrender.com/chat";
const COBY_UI_INSTRUCTIONS={
    name:"COBY markup",
    system:"COBY 답변은 아래 전용 마크업을 우선 사용한다. ***텍스트***는 굵게, <<<내용>>>은 사용자가 한 번에 복사할 내용이나 코드, [[[내용]]]은 주의/경고, {{{내용}}}은 성공/완료, (((내용)))은 팁, ---는 구분선이다. 마크업 기호 자체를 설명문으로 노출하지 않는다. 코드 복사에는 Markdown ``` 코드펜스를 사용하지 않고 <<< >>>를 사용한다. 일반적인 설명은 COBY의 본문형 답변으로 작성하고, 필요한 경우에만 마크업을 사용한다.",
    rules:["***text*** = bold","<<<content>>> = copy block","[[[content]]] = warning","{{{content}}} = success","(((content))) = tip","--- = divider","Do not expose the markup delimiters as an explanation","Use <<< >>> instead of Markdown triple-backtick code fences","Keep normal explanations as readable COBY body text"]
};
let currentUserId=null,currentPerson=null,currentConversationId=null,currentProjectId=null,currentProject=null,isSending=false;
const $=id=>document.getElementById(id);
const people=()=>collection(db,"people",currentUserId,"conversations");
const projects=()=>collection(db,"people",currentUserId,"projects");
const messagesRef=()=>collection(db,"people",currentUserId,"conversations",currentConversationId,"messages");
const escapeHtml=text=>String(text).replace(/[&<>\"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[ch]));
function setStatus(text,connected=false){$("statusText").textContent=text;$("statusDot").classList.toggle("connected",connected)}
function updateProfile(){const name=currentPerson?.name||currentUserId||"사용자";$("profileName").textContent=name;$("profileId").textContent=currentUserId?`학번 ${currentUserId}`:"-";$("profileCircle").textContent=name.charAt(0)}
function formatDate(timestamp){if(!timestamp)return"";const date=timestamp.toDate?timestamp.toDate():new Date(timestamp);return date.toLocaleDateString("ko-KR",{month:"numeric",day:"numeric"})}
function openMenu(){$("sidebar").classList.add("open");$("overlay").classList.add("show")}
function closeMenu(){$("sidebar").classList.remove("open");$("overlay").classList.remove("show")}
window.openMenu=openMenu;window.closeMenu=closeMenu;
function clearMessages(){$("messages").innerHTML=""}
function addMessage(role,content){const element=document.createElement("div");const isUser=role==="user";element.className=`message ${isUser?"user":"ai"}`;if(isUser){element.innerHTML=`<div class="message-label">YOU</div><div class="message-content">${escapeHtml(content)}</div>`}else{element.innerHTML=`<div class="message-label">COBY</div><div class="message-content">${renderCobyMarkup(content)}</div>`;addAnswerCopyButton(element,content,plainCobyText(content))}$("messages").appendChild(element);requestAnimationFrame(()=>{$("messages").scrollTop=$("messages").scrollHeight})}
function showWelcome(){clearMessages();const e=document.createElement("div");e.className="welcome";e.id="welcome";e.innerHTML='<h2>어서오세요!</h2><p>무한한 상상의 나래를 펼쳐요 🚀<br>Coby가 당신의 코딩 여정을 함께합니다.</p>';$('messages').appendChild(e)}
async function loadUser(){currentUserId=localStorage.getItem("userId");if(!currentUserId){setStatus("로그인이 필요합니다");updateProfile();return false}try{const s=await getDoc(doc(mainDb,"users",currentUserId));currentPerson=s.exists()?{schoolNumber:currentUserId,...s.data()}:{schoolNumber:currentUserId};await setDoc(doc(db,"people",currentUserId),{schoolNumber:currentUserId,name:currentPerson.name||"사용자",updatedAt:serverTimestamp()},{merge:true});updateProfile();setStatus(`${currentPerson.name||"사용자"}님`,true);await Promise.all([loadChats(),loadProjects()]);return true}catch(e){console.error(e);setStatus("Firebase 연결 실패");updateProfile();alert("Coby Firebase 연결에 실패했습니다.\n\nFirestore 보안 규칙도 확인해주세요.");return false}}
async function deleteConversation(id){if(!currentUserId||!id)return;try{const msgSnap=await getDocs(collection(db,"people",currentUserId,"conversations",id,"messages"));await Promise.all(msgSnap.docs.map(m=>deleteDoc(m.ref)));await deleteDoc(doc(db,"people",currentUserId,"conversations",id));if(currentConversationId===id){currentConversationId=null;await createConversation(currentProjectId)}else await loadChats()}catch(e){console.error(e);alert("채팅 삭제에 실패했습니다.")}}
async function loadChats(){if(!currentUserId)return;const s=await getDocs(query(people(),orderBy("updatedAt","desc"),limit(30)));$("chatList").innerHTML="";if(s.empty){$("chatList").innerHTML='<div class="empty-chat">아직 대화가 없습니다.</div>';return}s.forEach(item=>{const data=item.data(),e=document.createElement("div");e.className="chat-item"+(item.id===currentConversationId?" active":"");e.onclick=()=>openConversation(item.id);e.innerHTML=`<div class="chat-title">${escapeHtml(data.title||"새 대화")}</div><div class="chat-date">${formatDate(data.updatedAt)}</div><button type="button" class="chat-delete" aria-label="채팅 삭제">×</button>`;e.querySelector(".chat-delete").onclick=async ev=>{ev.preventDefault();ev.stopPropagation();if(confirm("이 채팅을 삭제할까요?"))await deleteConversation(item.id)};$("chatList").appendChild(e)})}
async function loadProjects(){if(!currentUserId)return;const s=await getDocs(query(projects(),orderBy("updatedAt","desc"),limit(30)));$("projectList").innerHTML="";if(s.empty){$("projectList").innerHTML='<div class="empty-chat">프로젝트가 없습니다.</div>';return}s.forEach(item=>{const data=item.data(),e=document.createElement("div");e.className="project-item"+(item.id===currentProjectId?" active":"");e.textContent="📁 "+(data.name||"이름 없음");e.onclick=()=>selectProject(item.id,data);$("projectList").appendChild(e)})}
async function createConversation(projectId=null){const r=await addDoc(people(),{title:"새 대화",projectId:projectId||null,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});currentConversationId=r.id;currentProjectId=projectId||null;showWelcome();await loadChats();return r.id}
async function newChat(){if(!currentUserId){alert("먼저 로그인해주세요.");return}await createConversation(currentProjectId);closeMenu();$("userInput").focus()}window.newChat=newChat;
async function openConversation(id){if(!currentUserId)return;currentConversationId=id;const cs=await getDoc(doc(db,"people",currentUserId,"conversations",id));if(!cs.exists())return;const c=cs.data();currentProjectId=c.projectId||null;currentProject=null;if(currentProjectId){const ps=await getDoc(doc(db,"people",currentUserId,"projects",currentProjectId));if(ps.exists())currentProject=ps.data()}const ms=await getDocs(query(messagesRef(),orderBy("createdAt","asc")));clearMessages();if(ms.empty)showWelcome();else ms.forEach(item=>{const m=item.data();addMessage(m.role,m.content)});await loadChats();await loadProjects();closeMenu()}
async function selectProject(id,data){currentProjectId=id;currentProject=data;await createConversation(id);await loadProjects();closeMenu()}window.selectProject=selectProject;
function openProjectModal(){$("projectModal").classList.add("show");$("projectNameInput").focus()}function closeProjectModal(){$("projectModal").classList.remove("show");$("projectNameInput").value="";$("projectDescriptionInput").value=""}window.openProjectModal=openProjectModal;window.closeProjectModal=closeProjectModal;
async function createProject(){if(!currentUserId){alert("먼저 로그인해주세요.");return}const name=$("projectNameInput").value.trim(),description=$("projectDescriptionInput").value.trim();if(!name){alert("프로젝트 이름을 입력하세요.");return}try{const r=await addDoc(projects(),{name,description,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});closeProjectModal();await loadProjects();await createConversation(r.id);closeMenu()}catch(e){console.error(e);alert("프로젝트 생성에 실패했습니다.")}}window.createProject=createProject;
async function getProjectContext(){if(!currentProjectId||!currentUserId)return[];try{const cs=await getDocs(query(people(),orderBy("updatedAt","desc"),limit(10))),context=[];for(const c of cs.docs){const d=c.data();if(d.projectId!==currentProjectId||c.id===currentConversationId)continue;const ms=await getDocs(query(collection(db,"people",currentUserId,"conversations",c.id,"messages"),orderBy("createdAt","desc"),limit(6)));[...ms.docs].reverse().forEach(m=>{const x=m.data();context.push({role:x.role,content:x.content})})}return context.slice(-30)}catch(e){console.warn("프로젝트 컨텍스트 로드 실패",e);return[]}}
async function sendMessage(){if(isSending)return;const input=$("userInput"),text=input.value.trim();if(!text)return;if(!currentUserId){alert("먼저 로그인해주세요.");return}if(!currentConversationId)await createConversation(currentProjectId);isSending=true;$("sendButton").disabled=true;if($("welcome"))$("welcome").remove();addMessage("user",text);input.value="";input.style.height="auto";try{await addDoc(messagesRef(),{role:"user",content:text,createdAt:serverTimestamp()});const ref=doc(db,"people",currentUserId,"conversations",currentConversationId),snap=await getDoc(ref);if(snap.exists()){const c=snap.data();await updateDoc(ref,{title:(!c.title||c.title==="새 대화")?(text.length>35?text.slice(0,35)+"…":text):c.title,updatedAt:serverTimestamp()})}const context=await getProjectContext();const response=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,studentId:currentUserId,userId:currentUserId,conversationId:currentConversationId,projectId:currentProjectId,project:currentProject||null,context,uiInstructions:COBY_UI_INSTRUCTIONS,systemPrompt:COBY_UI_INSTRUCTIONS.system})});if(!response.ok)throw new Error(`API ${response.status}`);const data=await response.json();const answer=data.answer??data.reply??data.response??data.message??"응답을 받지 못했습니다.";addMessage("assistant",answer);await addDoc(messagesRef(),{role:"assistant",content:answer,createdAt:serverTimestamp()});await updateDoc(ref,{updatedAt:serverTimestamp()});await loadChats()}catch(e){console.error("AI 요청 오류:",e);addMessage("assistant","죄송해요. 응답을 가져오는 중 오류가 발생했어요.\n잠시 후 다시 시도해주세요.")}finally{isSending=false;$("sendButton").disabled=false;input.focus()}}
window.sendMessage=sendMessage;
initCobyInput({input:$("userInput"),send:sendMessage});bindCobyCopy(document);
$("projectNameInput").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();createProject()}});
$("projectModal").addEventListener("click",e=>{if(e.target===$("projectModal"))closeProjectModal()});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeMenu();closeProjectModal()}});
(async()=>{const ok=await loadUser();if(!ok)return;try{const s=await getDocs(query(people(),orderBy("updatedAt","desc"),limit(1)));if(!s.empty)await openConversation(s.docs[0].id);else await createConversation(null)}catch(e){console.error("초기 대화 로드 실패:",e);await createConversation(null)}})();
