import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc, collection, addDoc, getDocs, query, orderBy, limit, serverTimestamp, updateDoc, deleteDoc } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { renderCobyMarkup, plainCobyText, bindCobyCopy } from "./coby-markup.js";
import { initCobyInput } from "./input.js";
import { addAnswerCopyButton } from "./chat-ui.js";

const mainFirebaseConfig={apiKey:"AIzaSyBgOAO72ArbW8dO7OSYsTVEQtRHT049U20",authDomain:"points2026-f5e50.firebaseapp.com",projectId:"points2026-f5e50",storageBucket:"points2026-f5e50.firebasestorage.app",messagingSenderId:"248724251417",appId:"1:248724251417:web:02d85cdc4addac98069b88"};
const cobyFirebaseConfig={apiKey:"AIzaSyAiO65YzYeRfuf6fCzosuW7OAVV47o47Js",authDomain:"coby-ai-328dd.firebaseapp.com",projectId:"coby-ai-328dd",storageBucket:"coby-ai-328dd.firebasestorage.app",messagingSenderId:"865530259286",appId:"1:248724251417:web:6feaa5781dc538700b18f7"};
const mainDb=getFirestore(initializeApp(mainFirebaseConfig,"mainApp"));
const db=getFirestore(initializeApp(cobyFirebaseConfig,"cobyApp"));
const API_URL="https://two5withcoding.onrender.com/chat";
const COBY_UI_INSTRUCTIONS={name:"COBY markup",system:"COBY 답변은 아래 전용 마크업을 우선 사용한다. ***텍스트***는 굵게, <<<내용>>>은 사용자가 한 번에 복사할 내용이나 코드, [[[내용]]]은 주의/경고, {{{내용}}}은 성공/완료, (((내용)))은 팁, ---는 구분선이다. 마크업 기호 자체를 설명문으로 노출하지 않는다. 코드 복사에는 Markdown ``` 코드펜스를 사용하지 않고 <<< >>>를 사용한다. 일반적인 설명은 COBY의 본문형 답변으로 작성하고, 필요한 경우에만 마크업을 사용한다.",rules:["***text*** = bold","<<<content>>> = copy block","[[[content]]] = warning","{{{content}}} = success","(((content))) = tip","--- = divider","Do not expose the markup delimiters as an explanation","Use <<< >>> instead of Markdown triple-backtick code fences","Keep normal explanations as readable COBY body text"]};

let currentUserId=null,currentPerson=null,currentConversationId=null,currentProjectId=null,currentProject=null,isSending=false;
const $=id=>document.getElementById(id);
const people=()=>collection(db,"people",currentUserId,"conversations");
const projects=()=>collection(db,"people",currentUserId,"projects");
const messagesRef=()=>collection(db,"people",currentUserId,"conversations",currentConversationId,"messages");
const conversationsRoot=uid=>collection(db,"people",uid,"conversations");
const escapeHtml=text=>String(text??"").replace(/[&<>\"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[ch]));
const isAdmin=()=>currentPerson?.role==="president"||currentPerson?.role==="vice";

function setStatus(text,connected=false){$("statusText").textContent=text;$("statusDot").classList.toggle("connected",connected)}
function updateProfile(){const name=currentPerson?.name||currentUserId||"사용자";$("profileName").textContent=name;$("profileId").textContent=currentUserId?`학번 ${currentUserId}`:"-";$("profileCircle").textContent=name.charAt(0)}
function formatDate(timestamp){if(!timestamp)return"";const date=timestamp.toDate?timestamp.toDate():new Date(timestamp);return date.toLocaleString("ko-KR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}
function openMenu(){$("sidebar").classList.add("open");$("overlay").classList.add("show")}
function closeMenu(){$("sidebar").classList.remove("open");$("overlay").classList.remove("show")}
window.openMenu=openMenu;window.closeMenu=closeMenu;
function clearMessages(){$("messages").innerHTML=""}

function addMessage(role,content){const element=document.createElement("div"),isUser=role==="user";element.className=`message ${isUser?"user":"ai"}`;if(isUser)element.innerHTML=`<div class="message-label">YOU</div><div class="message-content">${escapeHtml(content)}</div>`;else{element.innerHTML=`<div class="message-label">COBY</div><div class="message-content">${renderCobyMarkup(content)}</div>`;addAnswerCopyButton(element,content,plainCobyText(content))}$("messages").appendChild(element);requestAnimationFrame(()=>{$("messages").scrollTop=$("messages").scrollHeight})}
function showWelcome(){clearMessages();const e=document.createElement("div");e.className="welcome";e.id="welcome";e.innerHTML='<h2>어서오세요!</h2><p>무한한 상상의 나래를 펼쳐요 🚀<br>Coby가 당신의 코딩 여정을 함께합니다.</p>';$('messages').appendChild(e)}

async function loadUser(){currentUserId=localStorage.getItem("userId");if(!currentUserId){setStatus("로그인이 필요합니다");updateProfile();return false}try{const s=await getDoc(doc(mainDb,"users",currentUserId));currentPerson=s.exists()?{schoolNumber:currentUserId,...s.data()}:{schoolNumber:currentUserId};await setDoc(doc(db,"people",currentUserId),{schoolNumber:currentUserId,name:currentPerson.name||"사용자",role:currentPerson.role||"student",updatedAt:serverTimestamp()},{merge:true});updateProfile();setStatus(`${currentPerson.name||"사용자"}님`,true);await Promise.all([loadChats(),loadProjects()]);return true}catch(e){console.error(e);setStatus("Firebase 연결 실패");updateProfile();alert("Coby Firebase 연결에 실패했습니다.\n\nFirestore 보안 규칙도 확인해주세요.");return false}}

async function moveToTrash(id){if(!currentUserId||!id)return;try{await updateDoc(doc(db,"people",currentUserId,"conversations",id),{isDeleted:true,deletedAt:serverTimestamp(),deletedBy:currentUserId,updatedAt:serverTimestamp()});if(currentConversationId===id){currentConversationId=null;await createConversation(currentProjectId)}else await loadChats()}catch(e){console.error(e);alert("휴지통으로 이동하지 못했습니다.")}}
async function restoreConversation(id){if(!currentUserId||!id)return;try{await updateDoc(doc(db,"people",currentUserId,"conversations",id),{isDeleted:false,restoredAt:serverTimestamp(),updatedAt:serverTimestamp()});await loadTrash();await loadChats()}catch(e){console.error(e);alert("대화 복구에 실패했습니다.")}}
async function deleteConversationFromDb(uid,id){if(!isAdmin()||!uid||!id)return false;try{const msgSnap=await getDocs(collection(db,"people",uid,"conversations",id,"messages"));await Promise.all(msgSnap.docs.map(m=>deleteDoc(m.ref)));await deleteDoc(doc(db,"people",uid,"conversations",id));return true}catch(e){console.error(e);return false}}

async function loadChats(){if(!currentUserId)return;const s=await getDocs(query(people(),orderBy("updatedAt","desc"),limit(50)));$("chatList").innerHTML="";const docs=s.docs.filter(item=>!item.data().isDeleted);if(!docs.length){$("chatList").innerHTML='<div class="empty-chat">아직 대화가 없습니다.</div>';return}docs.forEach(item=>{const data=item.data(),e=document.createElement("div");e.className="chat-item"+(item.id===currentConversationId?" active":"");e.onclick=()=>openConversation(item.id);e.innerHTML=`<div class="chat-title">${escapeHtml(data.title||"새 대화")}</div><div class="chat-date">${formatDate(data.updatedAt)}</div><button type="button" class="chat-delete" aria-label="휴지통으로 이동">🗑</button>`;e.querySelector(".chat-delete").onclick=async ev=>{ev.preventDefault();ev.stopPropagation();if(confirm("이 대화를 휴지통으로 이동할까요?"))await moveToTrash(item.id)};$("chatList").appendChild(e)})}
async function loadTrash(){if(!currentUserId)return;const s=await getDocs(query(people(),orderBy("updatedAt","desc"),limit(100)));const docs=s.docs.filter(item=>item.data().isDeleted);$("trashList").innerHTML="";if(!docs.length){$("trashList").innerHTML='<div class="empty-chat">휴지통이 비어 있습니다.</div>';return}docs.forEach(item=>{const d=item.data(),e=document.createElement("div");e.className="system-item";e.innerHTML=`<div><strong>${escapeHtml(d.title||"새 대화")}</strong><div class="system-meta">삭제됨 ${formatDate(d.deletedAt||d.updatedAt)}</div></div><button class="restore-btn" type="button">복구</button>`;e.querySelector(".restore-btn").onclick=()=>restoreConversation(item.id);$("trashList").appendChild(e)})}
async function openTrash(){closeMenu();$("trashModal").classList.add("show");$("trashModal").setAttribute("aria-hidden","false");await loadTrash()}
function closeTrash(){$("trashModal").classList.remove("show");$("trashModal").setAttribute("aria-hidden","true")}
window.openTrash=openTrash;window.closeTrash=closeTrash;

async function loadAdminLogs(){if(!isAdmin()){alert("관리자 권한이 필요합니다.");return}const list=$("adminLogsList");list.innerHTML='<div class="empty-chat">로그를 불러오는 중...</div>';try{const users=await getDocs(collection(db,"people"));const rows=[];for(const u of users.docs){const uid=u.id;const cs=await getDocs(query(conversationsRoot(uid),orderBy("updatedAt","desc"),limit(100)));for(const c of cs.docs){const d=c.data();const ms=await getDocs(query(collection(db,"people",uid,"conversations",c.id,"messages"),orderBy("createdAt","asc"),limit(100)));rows.push({uid,cid:c.id,data:d,messages:ms.docs.map(m=>m.data())})}}rows.sort((a,b)=>(b.data.updatedAt?.toMillis?.()||0)-(a.data.updatedAt?.toMillis?.()||0));list.innerHTML="";if(!rows.length){list.innerHTML='<div class="empty-chat">대화 로그가 없습니다.</div>';return}rows.forEach(row=>{const e=document.createElement("article");e.className="admin-log-item";const messagesHtml=row.messages.map(m=>`<div class="admin-log-message"><b>${m.role==="user"?"사용자":"COBY"}</b><div>${escapeHtml(plainCobyText(m.content||""))}</div></div>`).join("");e.innerHTML=`<div class="admin-log-head"><div><strong>${escapeHtml(row.data.title||"새 대화")}</strong><div class="system-meta">사용자: ${escapeHtml(row.uid)} · ${formatDate(row.data.updatedAt)} ${row.data.isDeleted?"· 휴지통":""}</div></div><button class="danger-btn" type="button">DB 삭제</button></div><details class="admin-log-details"><summary>대화 내용 보기 (${row.messages.length}개)</summary><div class="admin-log-messages">${messagesHtml||'<div class="empty-chat">메시지가 없습니다.</div>'}</div></details>`;e.querySelector(".danger-btn").onclick=async()=>{if(!confirm(`'${row.data.title||"새 대화"}'의 대화와 메시지를 Firebase에서 영구 삭제할까요?`))return;const b=e.querySelector(".danger-btn");b.disabled=true;const ok=await deleteConversationFromDb(row.uid,row.cid);if(!ok){alert("DB 삭제에 실패했습니다.");b.disabled=false;return}e.remove();if(row.uid===currentUserId&&row.cid===currentConversationId){currentConversationId=null;await createConversation(currentProjectId)}await loadChats();await loadTrash()};list.appendChild(e)})}catch(e){console.error(e);list.innerHTML='<div class="empty-chat">로그를 불러오지 못했습니다. Firestore 권한을 확인해주세요.</div>'}}
async function openAdminLogs(){if(!isAdmin()){alert("관리자 권한이 필요합니다.");return}closeMenu();$("adminLogsModal").classList.add("show");$("adminLogsModal").setAttribute("aria-hidden","false");await loadAdminLogs()}
function closeAdminLogs(){$("adminLogsModal").classList.remove("show");$("adminLogsModal").setAttribute("aria-hidden","true")}
window.openAdminLogs=openAdminLogs;window.closeAdminLogs=closeAdminLogs;window.loadAdminLogs=loadAdminLogs;

async function loadProjects(){if(!currentUserId)return;const s=await getDocs(query(projects(),orderBy("updatedAt","desc"),limit(50)));const list=$("projectList");list.innerHTML="";if(!s.docs.length){list.innerHTML='<div class="empty-chat">프로젝트가 없습니다.</div>';return}s.docs.forEach(item=>{const d=item.data(),e=document.createElement("div");e.className="project-item"+(item.id===currentProjectId?" active":"");e.innerHTML=`<div>${escapeHtml(d.name||"이름 없는 프로젝트")}</div><div class="chat-date">${escapeHtml(d.description||"")}</div>`;e.onclick=()=>selectProject(item.id,d);list.appendChild(e)})}

async function createConversation(projectId=null){const r=await addDoc(people(),{title:"새 대화",projectId:projectId||null,isDeleted:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});currentConversationId=r.id;currentProjectId=projectId||null;showWelcome();await loadChats();return r.id}
async function newChat(){if(!currentUserId){alert("먼저 로그인해주세요.");return}await createConversation(currentProjectId);closeMenu();$("userInput").focus()}
window.newChat=newChat;

async function openConversation(id){if(!currentUserId)return;const cs=await getDoc(doc(db,"people",currentUserId,"conversations",id));if(!cs.exists()||cs.data().isDeleted)return;currentConversationId=id;const c=cs.data();currentProjectId=c.projectId||null;currentProject=null;if(currentProjectId){const ps=await getDoc(doc(db,"people",currentUserId,"projects",currentProjectId));if(ps.exists())currentProject=ps.data()}const ms=await getDocs(query(messagesRef(),orderBy("createdAt","asc")));clearMessages();if(ms.empty)showWelcome();else ms.forEach(item=>{const m=item.data();addMessage(m.role,m.content)});await loadChats();await loadProjects();closeMenu()}
async function selectProject(id,data){currentProjectId=id;currentProject=data;await createConversation(id);await loadProjects();closeMenu()}
window.selectProject=selectProject;
function openProjectModal(){$("projectModal").classList.add("show");$("projectNameInput").focus()}
function closeProjectModal(){$("projectModal").classList.remove("show");$("projectNameInput").value="";$("projectDescriptionInput").value=""}
window.openProjectModal=openProjectModal;window.closeProjectModal=closeProjectModal;

async function createProject(){if(!currentUserId){alert("먼저 로그인해주세요.");return}const name=$("projectNameInput").value.trim(),description=$("projectDescriptionInput").value.trim();if(!name){alert("프로젝트 이름을 입력하세요.");return}try{const r=await addDoc(projects(),{name,description,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});closeProjectModal();await loadProjects();await createConversation(r.id);closeMenu()}catch(e){console.error(e);alert("프로젝트 생성에 실패했습니다.")}}
window.createProject=createProject;

async function getProjectContext(){if(!currentProjectId||!currentUserId)return[];try{const cs=await getDocs(query(people(),orderBy("updatedAt","desc"),limit(20))),context=[];for(const c of cs.docs){const d=c.data();if(d.projectId!==currentProjectId||c.id===currentConversationId||d.isDeleted)continue;const ms=await getDocs(query(collection(db,"people",currentUserId,"conversations",c.id,"messages"),orderBy("createdAt","desc"),limit(6)));[...ms.docs].reverse().forEach(m=>{const x=m.data();context.push({role:x.role,content:x.content})})}return context.slice(-30)}catch(e){console.warn("프로젝트 컨텍스트 로드 실패",e);return[]}}
async function getConversationHistory(){if(!currentConversationId)return[];const s=await getDocs(query(messagesRef(),orderBy("createdAt","asc"),limit(40)));return s.docs.map(item=>{const m=item.data();return{role:m.role,content:m.content}})}
function extractAssistantText(data){return data?.reply??data?.response??data?.message??data?.content??data?.answer??"응답을 받지 못했습니다."}

async function sendMessage(){if(isSending)return;const input=$("userInput"),text=input.value.trim();if(!text)return;if(!currentUserId){alert("먼저 로그인해주세요.");return}if(!currentConversationId)await createConversation(currentProjectId);isSending=true;$("sendButton").disabled=true;if($("welcome"))$("welcome").remove();const history=await getConversationHistory(),projectContext=await getProjectContext();addMessage("user",text);input.value="";input.style.height="auto";try{await addDoc(messagesRef(),{role:"user",content:text,createdAt:serverTimestamp()});const conversationReference=doc(db,"people",currentUserId,"conversations",currentConversationId);const conversationSnapshot=await getDoc(conversationReference);if(conversationSnapshot.exists()){const conversation=conversationSnapshot.data();await updateDoc(conversationReference,{title:conversation.title&&conversation.title!=="새 대화"?conversation.title:(text.length>35?text.slice(0,35)+"…":text),updatedAt:serverTimestamp()})}const response=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,studentId:currentUserId,userId:currentUserId,conversationId:currentConversationId,projectId:currentProjectId,project:currentProject||null,context:projectContext,history,projectContext,user:{id:currentUserId,name:currentPerson?.name||"사용자",role:currentPerson?.role||"student"},uiInstructions:COBY_UI_INSTRUCTIONS})});if(!response.ok)throw new Error(`API ${response.status}`);const result=await response.json(),answer=String(extractAssistantText(result));addMessage("assistant",answer);await addDoc(messagesRef(),{role:"assistant",content:answer,createdAt:serverTimestamp()});await updateDoc(conversationReference,{updatedAt:serverTimestamp()});await loadChats()}catch(e){console.error("AI 요청 오류:",e);addMessage("assistant",`[[[COBY 응답을 가져오지 못했습니다.]]]\n\n${e.message||"잠시 후 다시 시도해주세요."}`)}finally{isSending=false;$("sendButton").disabled=false;input.focus()}}
window.sendMessage=sendMessage;

async function initializeConversation(){if(!currentUserId)return;try{const s=await getDocs(query(people(),orderBy("updatedAt","desc"),limit(50)));const latest=s.docs.find(item=>!item.data().isDeleted);if(latest)await openConversation(latest.id);else await createConversation(null)}catch(e){console.error("초기 대화 로드 실패:",e);showWelcome()}}

function init(){bindCobyCopy(document);initCobyInput({input:$("userInput"),send:sendMessage});$("projectNameInput").addEventListener("keydown",event=>{if(event.key==="Enter")createProject()});document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeMenu();closeProjectModal();closeTrash();closeAdminLogs()}});$("projectModal").addEventListener("click",event=>{if(event.target===$("projectModal"))closeProjectModal()});$("trashModal").addEventListener("click",event=>{if(event.target===$("trashModal"))closeTrash()});$("adminLogsModal").addEventListener("click",event=>{if(event.target===$("adminLogsModal"))closeAdminLogs()});loadUser().then(success=>{if(success)initializeConversation()})}
init();
